name: Jira Find issue key
description: Find an issue inside event
branding:
    icon: 'book-open'
    color: 'blue'
inputs:
    event:
        description: Provide jsonpath for the GitHub event to extract issue from
        required: false
    string:
        description: Provide a string to extract issue key from
        required: false
    from:
        description: Find from predefined place (should be either 'branch', or 'commits', default is 'commits')
        required: false
        default: commits
    allowlist:
        description: The emails of the users that this check should not be valid
        required: false
    repo-token:
        description: Provide the token for the current repository
        required: false
outputs:
    issue:
        description: Key of the found issue
runs:
    using: 'node12'
    main: './dist/index.js'
